config/routes.rb
BloggingApp::Application.routes.draw do
  devise_for :users
  

  root "posts#index"

  resources :posts do
    resources :comments
    resources :votes
    member do
      get :delete
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :comments

	has_many :votes

	def votes_total
		return 0 if (upvotes + downvotes).empty?
		upvotes.size - downvotes.size
	end
		
	def upvotes
		votes.up
	end

	def downvotes
		votes.down
	end
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post

  scope :up, -> { where(direction: 'up') }
 	scope :down, -> { where(direction: 'down') }
 	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def new
		@post = Post.find(params[:post_id])
	end

	def create
		@post = Post.find(params[:post_id])

		@post.comments.create(params[:comment].permit(:body))
		flash[:notice] = 'Comment saved'
		redirect_to '/posts'
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]

	def index
		 @posts = Post.all
	end

	def new
		# authenticate_user!
		@post = Post.new

	end

	def create
		# authenticate_user!
		@post = Post.create(params[:post].permit(:title, :body))
		flash[:notice] = 'Post saved'
		redirect_to @post
		# redirect_to post_path(@post)
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find params[:id]
	end

	def update
		@post = Post.find params[:id]
		puts "params[:id]: #{params[:id]}"
		@post.update(params[:post].permit(:title, :body))
		redirect_to '/posts'
	end

	def destroy
	  @post = Post.find(params[:id])
	  @post.destroy
	  redirect_to posts_path
	end

	def delete
		@post = Post.find(params[:id])
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		#authenticate_user!
		# raise params.inspect
 		@post = Post.find params[:post_id]
 	  @post.votes.create(direction: params[:direction])
 		#redirect_to '/posts'
 		render json: { id: @post.id, votes: @post.votes_total }
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def vote_button(post, direction, link_text)
    button_to link_text, post_votes_path(post, direction: direction), remote: true
  end
  
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, Comment.new] do |f| %>

<p>
	<%= f.label :body %>
	<%= f.text_area :body %>
</p>

<p>
<%= f.submit 'Submit Comment' %>
</p>

<% end %>

app/views/home/index.html.erb
<p> hello! </p>

<br>

<%= link_to 'Create Post', new_post_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BloggingApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :body %>
	<%= f.text_area :body %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/delete.html.erb
<%= form_for @post, url: post_path(@post), method: :delete do |f| %>

<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :bodys %>
	<%= f.text_area :body %>
</p>

<p>
<%= f.submit 'Confirm Delete!' %>
</p>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= Time.now %>

<br>
<br>



<%= link_to 'Create Post', new_post_path %>

<br>
<h1>List of blog posts</h1>
 
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr class='post'>
      <td class="title">
        <strong>Blog Post:</strong>
      </td>
      <td><%= post.title.upcase %></td>
      <td><%= truncate(post.body, length:250, :separator => ' ') %></td>
      <td class="vote-count" data-id="<%= post.id %>">Votes: <%= post.votes_total %></td>
      <td><%= vote_button post, 'up', '▲' %></td>
      <td><%= vote_button post, 'down', '▼' %> </td>
      <td><%= link_to 'Full post', post %></td>
    	<td><%= link_to 'Edit', edit_post_path(post) %></td>
    	<td><%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    	<td><%= link_to 'Refined-delete', delete_post_path(post) %></td>
      <td><%= link_to 'Comment', new_post_comment_path(post) %></td>
    </tr>
  
      <% post.comments.each do |comment | %>
    <tr>
      <td>Comment:</td>
      <td></td>
      <td><strong><%= comment.body %></strong></td>
      <td>
        
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>


      <% end %>
    </tr>
  
  <% end %>

</table>

app/views/posts/index_draft.html.erb
<% @posts.each do |post| %>

<h1><%= post.title %></h1>

<%= post.body %>
<%= link_to 'Edit', edit_post_path(post) %>
<%-# link_to 'Delete', 'http://localhost:3000/posts/delete' %>

<%= link_to 'Refined delete', delete_post_path(post) %>
<%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>


<% post.comments.each do |comment | %>
<br>
<strong><%= comment.body %></strong>
<% end %>



<%= link_to 'Add comment', new_post_comment_path(post) %>

<% end %>





<%= link_to 'Create Post', new_post_path %>

<h1>Listing posts</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post %></td>
    	<td><%= link_to 'Edit', edit_post_path(post) %></td>
    	<td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    	<td><%= link_to 'Refined-delete', delete_post_path(post) %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.body %>
</p>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>
 
<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %>